version: "2.15.1"
services:
  ### Prefect Orion API
  server:
    image: levyvix/comandola_filmes:com_date
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: [ "prefect", "server", "start" ]
    environment:
      # If you want to access Prefect Server from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL to match the external hostname/IP used to load the  UI in your web browser.
      - PREFECT_UI_API_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
    ports:
      - 4200:4200

  agent:
    image: levyvix/comandola_filmes:com_date
    restart: always
    entrypoint: [ "prefect", "agent", "start", "-q", "dev" ]
    environment:
      - PREFECT_API_URL=http://127.0.0.1:4200/api

volumes:
  prefect:
