# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: scraper-filmes
prefect-version: 3.1.15

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.deployments.steps.git_clone:
    repository: https://github.com/levyvix/scraper-filmes.git
    branch: main

# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: gratis-torrent-scraper
  version: 1.0
  tags: ["scraper", "gratis-torrent", "movies"]
  concurrency_limit: 1
  description: "Daily scraper for GratisTorrent movies with database insertion"
  entrypoint: src/flows/prefect_flow_gratis.py:gratis_torrent_flow
  parameters:
    export_bq: true
  work_pool:
    name: default
    work_queue_name: null
    job_variables: {}
  schedules:
  - cron: '0 2 * * *'
    timezone: America/Sao_Paulo
    day_or: true
    active: true
