version: "3.7"

services:

  agent:
    build: .
    command: bash -c "prefect agent start -q dev"
    environment:
      PREFECT_API_URL: "http://172.17.0.1:4200/api"
    volumes:
      - /srv/docker/prefect/flows:/root/.prefect/flows
      - /srv/docker/prefect/flows:/flows
